<a href="https://colab.research.google.com/github/HelloPenguin1/Pytorch_learning/blob/main/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [10]:
a = [[1,2,3],[4,5,6]]
a_t = torch.tensor(a, dtype=torch.float32)

In [11]:
a_t

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Mean of each column, set dim=0 to collapse rows, one value per column

In [12]:
col_mean = torch.mean(a_t, dim=0)
print(col_mean)

tensor([2.5000, 3.5000, 4.5000])


Mean of each row, set dim=1 to collapse columns, one value per row

In [13]:
row_mean = torch.mean(a_t, dim=1)
print(row_mean)

tensor([2., 5.])


Mean of entire matrix

In [14]:
entire_mean = torch.mean(a_t)
print(entire_mean)

tensor(3.5000)
