<a href="https://colab.research.google.com/github/HelloPenguin1/Pytorch_learning/blob/main/Pytorch_Tutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

### Tensors
- A torch tensor is multi-dim matrix containing elements of a single data type
- Work better on GPUs
- default data type of float32
- more suitable for DL than a numpy array

In [3]:
tensor_2d = torch.randn(3)
tensor_2d

tensor([ 0.6044,  0.1595, -0.6851])

In [5]:
tensor = torch.arange(10)
tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
tensor2 = tensor.reshape(2,5)
tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
tensor3 = torch.arange(15)
tensor3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
tensor4 = tensor.reshape(-1, 2)

In [17]:
tensor4

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

Simple Neural Network

In [20]:
import torch.nn as nn #torch's neural network
import torch.nn.functional as F  #helps move data forward in a neural network

In [22]:
# create a model class that inherits nn.Module

In [30]:
class Model(nn.Module):
  #Input layer -> Hidden layer 1 (some num of neurons) -> Hl2 (some num of neurons) -> output layer
  def __init__(self, in_features = 4, h1 = 8, h2 = 9, out_features = 3):
    super().__init__() #instantiate our nn model


    self.fc1= nn.Linear(in_features, h1)     # fully connected layer 1 to linearly passes information from input to hidden layer 1
    self.fc2 = nn.Linear(h1, h2)             # to pass info for hidden 1 to hidden 2
    self.out = nn.Linear(h2, out_features)   # output layer to linearly pass info from h2 to output

  #function to move information
  def forward(self, x):
    x = F.relu(self.fc1(x))  #start with layer one
    x = F.relu(self.fc2(x))  #move to layer 2
    x = self.out(x)
    return x

In [31]:
torch.manual_seed(41)

In [32]:
#create an instance of the model
model = Model()